getliners: getliners.cpp
	g++ -O3 -o getliners getliners.cpp -lz
ieatgor:  ieatgorV2.cpp
	g++ -O3 -o ieatgor ieatgorV2.cpp -lz
VCFmergeGTF3: VCFmergeGTF3.cpp
	g++ -O3 -o VCFmergeGTF3 VCFmergeGTF3.cpp -lz
